language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: hhvm

addons:
  code_climate:
    repo_token: fccfe91d5ccd044b18f67fe21ce26760aa29979e969779358e75a7e43df57b5e

before_install:
  - cd ..
  - git clone https://github.com/neos/flow-base-distribution.git
  - cd flow-base-distribution
  - git checkout 3.1
  - composer update
  - composer require codeclimate/php-test-reporter:dev-master --dev
install:
  - mkdir -p Packages/Application/RFY.JWT
  - mv ../JWT/* Packages/Application/RFY.JWT
script:
  - bin/phpunit -c Packages/Application/RFY.JWT/UnitTests.xml --coverage-clover build/logs/clover.xml
  - bin/phpunit --stop-on-failure -c Packages/Application/RFY.JWT/UnitTests.xml --testsuite "RFY.JWT tests"
  - cd Packages/Application/RFY.JWT
  - ../../../bin/test-reporter